name: Naukri Resume Auto Update

# Run every 2 hours
on:
  schedule:
    - cron: '0 */2 * * *'  # every 2 hours
  workflow_dispatch:

jobs:
  update-resume:
    runs-on: ubuntu-latest
    env:
      NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
      NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      GITHUB_ACTIONS: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager python-dotenv

      - name: Run Naukri update script
        run: python naukri_update.py

      - name: Delete old workflow runs (keep latest 1)
        uses: peter-evans/delete-workflow-runs@v2
        with:
          workflow: Naukri Resume Auto Update
          keep-succeeded: 1
          keep-failed: 1

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Naukri Resume Updated ✅"
          body: "Your Naukri resume has been updated successfully."
          to: "your_email@gmail.com"
          secure: true
